[package]
name = "rid-pocket"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[workspace]

[features]
console-text = []

[dependencies]
odid = { path = "../crates/odid" }
rid-proto = { path = "../crates/rid-proto" }
esp-hal = { version = "~1.1", features = ["esp32s3", "unstable"] }
esp-rtos = { version = "~0.3.0", features = ["esp32s3", "embassy", "esp-alloc", "esp-radio"] }
esp-radio = { version = "~0.18.0", default-features = false, features = ["esp32s3", "wifi", "sniffer", "esp-alloc", "unstable"] }
esp-alloc = "~0.10.0"
esp-backtrace = { version = "~0.19.0", features = ["esp32s3", "panic-handler", "println"] }
esp-println = { version = "~0.17.0", default-features = false, features = ["esp32s3", "jtag-serial", "critical-section"] }
esp-bootloader-esp-idf = { version = "~0.5.0", features = ["esp32s3"] }
embassy-executor = "~0.10.0"
embassy-time = "~0.5.0"
embassy-sync = "~0.8.0"
embassy-futures = "~0.1.2"
embedded-io-async = "~0.7.0"
static_cell = "~2.1"
log = { version = "~0.4.29", features = ["release_max_level_info"] }
mipidsi = "~0.10.0"
embedded-graphics = "0.8"

[profile.dev]
opt-level = "s"
[profile.dev.package."*"]
opt-level = 3
[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
debug = 2
panic = "abort"
